# Generated by Django 4.2.20 on 2025-04-25 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0002_alter_postagem_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='date_added',
            new_name='data_adicionada',
        ),
        migrations.RenameField(
            model_name='postagem',
            old_name='data_postagem',
            new_name='data_adicionada',
        ),
        migrations.AddField(
            model_name='categoria',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
