# Generated by Django 4.2.20 on 2025-04-25 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0003_rename_date_added_categoria_data_adicionada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
