# Generated by Django 4.2.20 on 2025-05-05 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='postagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='blogs.postagem'),
        ),
    ]
